import React from 'react';
import Link from 'next/link';
import { format } from 'date-fns';

interface KnowledgeCardProps {
  title: string;
  slug: string;
  category?: string;
  summary?: string;
  excerpt: string;
  lastUpdated?: string;
  readingTime?: string;
  tags?: string[];
  complexity?: string;
  agent_author?: string;
}

const KnowledgeCard: React.FC<KnowledgeCardProps> = ({
  title,
  slug,
  category,
  summary,
  excerpt,
  lastUpdated,
  readingTime,
  tags,
  complexity,
  agent_author
}) => {
  return (
    <div className="p-6 border border-gray-100 rounded-lg shadow-sm hover:shadow-md transition-shadow">
      <div className="flex justify-between items-start mb-3">
        {category && (
          <span className="text-xs font-medium text-gray-500 uppercase tracking-wider">
            {category}
          </span>
        )}
        {complexity && (
          <span className="text-xs font-medium text-gray-500 uppercase tracking-wider">
            {complexity} complexity
          </span>
        )}
      </div>
      
      <Link href={`/knowledge/${slug}`}>
        <h3 className="text-xl font-bold mb-2 hover:underline">{title}</h3>
      </Link>
      
      <p className="text-gray-700 mb-4">{summary || excerpt}</p>
      
      <div className="flex flex-wrap gap-2 mb-4">
        {tags && tags.map(tag => (
          <span 
            key={tag} 
            className="px-2 py-1 bg-gray-100 text-gray-800 text-xs rounded"
          >
            {tag}
          </span>
        ))}
      </div>
      
      <div className="flex justify-between items-center text-sm text-gray-500 mt-auto">
        <div>
          {lastUpdated && (
            <span>Updated: {format(new Date(lastUpdated), 'MMM d, yyyy')}</span>
          )}
        </div>
        <div>
          {readingTime && <span>{readingTime}</span>}
        </div>
      </div>
      
      {agent_author && (
        <div className="mt-3 pt-3 border-t border-gray-100 text-xs text-gray-500">
          <span>Generated by: {agent_author}</span>
        </div>
      )}
    </div>
  );
};

export default KnowledgeCard;
