name: Pre-Merge Content & Build Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, staging, 'feature/*', 'fix/*' ]

jobs:
  validate-content-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Type Checks
      run: npm run type-check
      
    - name: Validate Content Structure
      run: npm run validate-content
      
    - name: Validate Prisma Imports
      run: npm run validate-prisma-imports
      
    - name: Build Application
      run: npm run build
      
    - name: Run Tests
      run: npm test
      
    - name: Security Audit
      run: npm audit --audit-level=high
      
    - name: Notify on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Generate Build Report
      if: failure()
      run: |
        echo "# 🚨 Build Validation Failed" > build-error-log.md
        echo "## Error Details" >> build-error-log.md
        echo "\`\`\`" >> build-error-log.md
        npm run build 2>&1 | tee -a build-error-log.md
        echo "\`\`\`" >> build-error-log.md
        
    - name: Upload Build Error Log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-error-log
        path: build-error-log.md
        retention-days: 5
